import React from 'react'

export default function AboutjijueScreen() {
  return (
    <div>
      <p  style={{fontWeight:"bold",fontSize:"25px",color:"#00478f", marginLeft:'42rem'}}>ABOUT US</p>
      <p style={{fontSize:"20px", marginLeft:'30rem'}}>
        Jijue is a platform where one can assess their risk of contracting</p>
      <p style={{fontSize:"20px", marginLeft:'30rem'}}>
        Hiv by undertaking a short assessment that involves a questionaire on different</p>
      <p style={{fontSize:"20px", marginLeft:'30rem'}}>
        risk factors that may make one vulnerable to contracting the virus. Questions asked</p>
      <p style={{fontSize:"20px", marginLeft:'30rem'}}>
        are based on real statistics on how Hiv is spread , sexual behaviours and even use of drug </p>
      <p style={{fontSize:"20px", marginLeft:'30rem'}}>
        substance between individuals mostly by shared syringe injection that is a culminating factor</p>
      <p style={{fontSize:"20px", marginLeft:'30rem'}}>
        in the spread of Hiv. After assessment, a risk score is auto-generated by our machine model that </p>
      <p style={{fontSize:"20px", marginLeft:'30rem'}}>
         shows your risk level and recommends ways to minimize chances of contracting the STD.</p>
      <p style={{fontWeight:"bold",fontSize:"25px",color:"#00478f", marginLeft:'42rem'}}>OUR MISSION</p>
      <p style={{fontSize:"20px", marginLeft:'30rem'}}>Create awareness on Hiv risk factors</p>
      <p style={{fontSize:"20px", marginLeft:'30rem'}}>To increase Hiv testing rates</p>
      <p style={{fontSize:"20px", marginLeft:'30rem'}}>to revolutionize approaches in Hiv prevention</p>

    </div>
  )
}
